pipeline {
    environment {
        dockerImageName = "juyel8968/mcb"
        dockerImage = ""
        registryCredential = 'dockerhub'
        containerName = 'mcbcontainer'
        containerPort = 8080
        hostPort = 8080
    }
    agent any
    stages {
        stage('Checkout Source') {
            steps {
                git credentialsId: 'github', url: 'https://github.com/juyelhushen/MCB.git'
            }
        }
        stage('Build image') {
            steps {
                script {
                    dockerImage = docker.build dockerImageName, "-f ./Dockerfile ."
                }
            }
        }
        stage('Pushing Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage('Create Container') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        docker.container(dockerImageName).withRun('-d -p ${hostPort}:${containerPort} --name ${containerName}') {
                            // Container creation steps if any
                        }
                    }
                }
            }
        }
    }
}
