pipeline {
  environment {
    dockerimagename = "juyel8968/mcb"
    dockerImage = ""
  }
  agent any
  stages {
    stage('Checkout Source') {
      steps {
        git credentialsId: 'github', url: 'https://github.com/juyelhushen/MCB.git'
      }
    }
    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename, "-f backend/Dockerfile ."
        }
      }
    }
    stage('Pushing Image') {
      environment {
        registryCredential = 'dockerhub'
      }
      steps{
        script {
          docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
            dockerImage.push("latest")
          }
        }
      }
    }
    stage('Create Docker Container') {
      steps {
        script {
          docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
            dockerImage.run("-p 8080:8080 --name mycontainer")
          }
        }
      }
    }
  }
}
