pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from GitHub
                git 'https://github.com/juyelhushen/MCB.git'
            }
        }

        stage('Docker Build') {
            steps {
                // Build the Docker image
                sh 'docker build -t mcb .'
            }
        }

        stage('Docker Run') {
            steps {
                // Create and run the Docker container
                sh 'docker run -d --name mcbcontainer -p 8080:8080 mcb'
            }
        }
    }
}
